# Linear Regression

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('simDTS2.csv')
new_data = data.groupby(['t']).agg(number = ('t','count'),dr=('y','sum'),edr=('pd','sum'),std = ('pd','std'))
data["dr"] = new_data["dr"]/new_data["number"]
data['c'] = data['v'] + data['t']
#data = pd.read_csv('src/visualization/simDTS.csv')

In [3]:
data

Unnamed: 0     key  t   v   x1  x2        h1        x4  del  y  ct  \
0                 1       1  1  33  616   0 -1.586784  0.973403    0  0  34   
1            100001       1  2  33  616   0 -0.823600  0.982014    0  0  35   
2            200001       1  3  33  616   0  1.123665  0.987872    0  0  36   
3            300001       1  4  33  616   0 -0.608673  0.991837    0  0  37   
4            399897       1  5  33  616   0 -1.559692  0.994514    0  0  38   
...             ...     ... ..  ..  ...  ..       ...       ...  ... ..  ..   
2275202      200000  100000  2  24  547   0  2.548360  0.598688    0  0  26   
2275203      300000  100000  3  24  547   0  1.716822  0.689974    0  0  27   
2275204      399896  100000  4  24  547   0  1.901394  0.768525    1  0  28   
2275205      499433  100000  5  24  547   0  2.321540  0.832018    2  0  29   
2275206      598426  100000  6  24  547   0  2.032616  0.880797    3  1  30   

                   pd        dr   c  
0        4.652029e-07       NaN  34  
1        6.726511e-05  0.000000  35  
2        6.164072e-04  0.000000  36  
3        1.794185e-03  0.001040  37  
4        2.992701e-03  0.003594  38  
...               ...       ...  ..  
2275202  2.035140e-04       NaN  26  
2275203  2.348893e-03       NaN  27  
2275204  8.333752e-03       NaN  28  
2275205  1.628851e-02       NaN  29  
2275206  2.287119e-02       NaN  30  

[2275207 rows x 14 columns]

In [3]:
from sklearn import model_selection
#x_train, x_test = model_selection.train_test_split(xList, test_size=0.2) 
#y_train, y_test = model_selection.train_test_split(data['x4'], test_size=0.2) 
train, test = model_selection.train_test_split(data, test_size=0.2) 
#print(train)

In [4]:
#train._get_value(1126070, 't')
print(test)

         Unnamed: 0    key   t   v   x1  x2        h1        x4  del  y  ct  \
1721756       75637  75637   1  14  615   0 -0.792434  0.017986    0  0  15   
1958073     1628407  86045  17  11  618   1 -0.396483  0.768525    0  0  28   
945661       341477  41523   4  35  590   0  1.762404  0.996316    0  0  39   
2097713     1169448  92183  12  18  554   0 -0.465951  0.880797    0  0  30   
1287569      945335  56578  10  30  554   1 -0.512216  0.997527    0  0  40   
...             ...    ...  ..  ..  ...  ..       ...       ...  ... ..  ..   
266474      1743405  11714  19  10  575   0  7.472806  0.832018    0  0  29   
591767      1106848  25995  12  26  594   0  0.686066  0.994514    0  0  38   
2213788     1730266  97287  18   4  569   0  4.112721  0.231475    0  0  22   
1180431     1780061  51858  19  12  584   1 -0.361537  0.916827    0  0  31   
1955487     1068880  85934  11   4  662   0 -5.530812  0.017986    0  0  15   

                   pd  dr   c  
1721756  1.200502e-

In [5]:

from operator import index


xTrain = []
for i in train.index:
    d = []
    d.append(train._get_value(i, 't'))
    #d.append(train['t'][i])
    d.append(train._get_value(i, 'v'))
    #d.append(train['v'][i])
    d.append(train._get_value(i, 'c'))
    xTrain.append(d)




xTest = []
for i in test.index:
    d = []
    d.append(test._get_value(i, 't'))
    #d.append(test['t'][i])
    d.append(test._get_value(i, 'v'))
    #d.append(test['v'][i])
    d.append(test._get_value(i, 'c'))
    xTest.append(d)


#yTrain = train['dr']
#yTest = test['dr']
yTrain = train['pd']
yTest = test['pd']

print(len(xTrain),len(xTest),len(yTrain),len(yTest))

1820165 455042 1820165 455042


In [10]:
train_encode_simplify = train[['v','t','c']]
train_encode = pd.get_dummies(train_encode_simplify,columns = ['v','t','c'])
test_encode_simplify = test[['v','t','c']]
test_encode = pd.get_dummies(test_encode_simplify,columns = ['v','t','c'])

In [7]:
xTrain[0]

[16, 10, 26]

### linear regression

In [11]:
##############encode
from sklearn import linear_model
reg=linear_model.LinearRegression(fit_intercept=True)
reg.fit(train_encode,yTrain)
print(reg.coef_,reg.intercept_)

print(reg.score(X=test_encode,y=yTest))
err = reg.predict(test_encode)-yTest
#np.mean(err)
#print(np.sqrt(np.mean(err**2)))

[-8.04142897e+05 -7.64810754e+05 -7.25478612e+05 -6.86146469e+05
 -6.46814327e+05 -6.07482184e+05 -5.68150041e+05 -5.28817899e+05
 -4.89485756e+05 -4.50153614e+05 -4.10821471e+05 -3.71489329e+05
 -3.32157186e+05 -2.92825043e+05 -2.53492900e+05 -2.14160758e+05
 -1.74828615e+05 -1.35496472e+05 -9.61643295e+04 -5.68321871e+04
 -1.75000444e+04  2.18320980e+04  6.11642403e+04  1.00496383e+05
  1.39828526e+05  1.79160667e+05  2.18492810e+05  2.57824952e+05
  2.97157094e+05  3.36489236e+05  3.75821378e+05  4.15153520e+05
  4.54485662e+05  4.93817805e+05  5.33149947e+05  1.66036628e+07
  1.66429949e+07  1.66823270e+07  1.67216592e+07  1.67609913e+07
  1.68003235e+07  1.68396556e+07  1.68789878e+07  1.69183199e+07
  1.69576520e+07  1.69969842e+07  1.70363163e+07  1.70756485e+07
  1.71149806e+07  1.71543128e+07  1.71936449e+07  1.72329770e+07
  1.72723092e+07  1.73116413e+07  1.73509735e+07  1.73903056e+07
  1.74296378e+07  1.74689699e+07  1.75083020e+07  1.51682992e+06
  1.47749778e+06  1.43816

In [12]:
from sklearn import linear_model
reg=linear_model.LinearRegression(fit_intercept=True)
reg.fit(xTrain,yTrain)
print(reg.coef_,reg.intercept_)

print(reg.score(X=xTest,y=yTest))
err = reg.predict(xTest)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err**2)))

[ 181911.59356944  181911.59372592 -181911.59358101] 0.0021709952464190945
0.03153737170721116
0.008161469748159789


In [9]:
print(reg.score(X=xTrain,y=yTrain))
err = reg.predict(xTrain)-yTrain
#np.mean(err)
print(np.sqrt(np.mean(err**2)))

0.03183881093902319
0.008139839592656134


### linear regression with regularization

###### alpha=1

In [10]:
from sklearn.linear_model import Ridge
clf1 = Ridge(alpha=1)
clf1.fit(xTrain,yTrain)
print(clf1.coef_,clf1.intercept_)

print(clf1.score(X=xTest,y=yTest))
err1 = clf1.predict(xTest)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err1**2)))

[-5.57674329e-05  1.00352793e-04  4.45853807e-05] 0.00216767228373503
0.03142497344753181
0.008208203549596761


###### alpha=10000

In [11]:
from sklearn.linear_model import Ridge
clf2 = Ridge(alpha=999)
clf2.fit(xTrain,yTrain)
print(clf2.coef_,clf2.intercept_)

print(clf2.score(X=xTest,y=yTest))
err2 = clf2.predict(xTest)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err2**2)))

[-5.57668319e-05  1.00352239e-04  4.45854073e-05] 0.00216767397134976
0.03142497268731759
0.008208203552817985


### one hot encoding

In [12]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

#### integer encoding

In [13]:
'''
label_encoder = LabelEncoder()
data['t_encode'] = label_encoder.fit_transform(data['t'])
print(data['t_encode'])
data['v_encode']  = label_encoder.fit_transform(data['v'])
print(data['v_encode'])
data['c_encode']  = label_encoder.fit_transform(data['c'])
print(data['c_encode'])


onehot_encoder = OneHotEncoder(handle_unknown='ignore')
onehot_encoded = onehot_encoder.fit_transform(data['t'])
print(onehot_encoded)
'''

"\nlabel_encoder = LabelEncoder()\ndata['t_encode'] = label_encoder.fit_transform(data['t'])\nprint(data['t_encode'])\ndata['v_encode']  = label_encoder.fit_transform(data['v'])\nprint(data['v_encode'])\ndata['c_encode']  = label_encoder.fit_transform(data['c'])\nprint(data['c_encode'])\n\n\nonehot_encoder = OneHotEncoder(handle_unknown='ignore')\nonehot_encoded = onehot_encoder.fit_transform(data['t'])\nprint(onehot_encoded)\n"

In [14]:
data_simplify = data[['v','t','c','dr']]
train_encode, test_encode = model_selection.train_test_split(data_simplify, test_size=0.2) 
train_encode

v   t   c  dr
1309877  13   6  19 NaN
1194084  13  12  25 NaN
1628576  32   3  35 NaN
1513883  16  10  26 NaN
593186   22  15  37 NaN
...      ..  ..  ..  ..
624238   15  11  26 NaN
1297382  15  15  30 NaN
1214855  35  20  55 NaN
569414   14   7  21 NaN
1313895   9  15  24 NaN

[1820165 rows x 4 columns]

In [15]:
# reference: https://blog.csdn.net/maymay_/article/details/80198468?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522166797260416782417051075%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=166797260416782417051075&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-2-80198468-null-null.142^v63^control,201^v3^control,213^v2^t3_esquery_v3&utm_term=pandas.get_dummies&spm=1018.2226.3001.4187
train_encode.columns = ['v','t','c','dr']
train_encode = pd.get_dummies(train_encode)
#pd.get_dummies(test_encode)
train_encode

v   t   c  dr
1309877  13   6  19 NaN
1194084  13  12  25 NaN
1628576  32   3  35 NaN
1513883  16  10  26 NaN
593186   22  15  37 NaN
...      ..  ..  ..  ..
624238   15  11  26 NaN
1297382  15  15  30 NaN
1214855  35  20  55 NaN
569414   14   7  21 NaN
1313895   9  15  24 NaN

[1820165 rows x 4 columns]

In [16]:
from operator import index


xTrain_encode = []
for i in train_encode.index:
    d = []
    d.append(train_encode._get_value(i, 't'))
    #d.append(train['t'][i])
    d.append(train_encode._get_value(i, 'v'))
    #d.append(train['v'][i])
    d.append(train_encode._get_value(i, 'c'))
    xTrain_encode.append(d)




xTest_encode = []
for i in test_encode.index:
    d = []
    d.append(test_encode._get_value(i, 't'))
    #d.append(test['t'][i])
    d.append(test_encode._get_value(i, 'v'))
    #d.append(test['v'][i])
    d.append(test_encode._get_value(i, 'c'))
    xTest_encode.append(d)


#yTrain = train['dr']
#yTest = test['dr']
#same as before
#yTrain = train['pd']
#yTest = test['pd']

#print(xTrain_encode[:10],xTest_encode[:10],yTrain[:10],yTest[:10])
print(len(xTrain_encode),len(xTest_encode),len(yTrain),len(yTest))

1820165 455042 1820165 455042


In [17]:
print(xTest_encode[:10])

[[12, 31, 43], [20, 18, 38], [21, 16, 37], [6, 9, 15], [1, 17, 18], [13, 16, 29], [5, 7, 12], [16, 3, 19], [13, 25, 38], [15, 2, 17]]


In [18]:
from sklearn import linear_model
reg=linear_model.LinearRegression(fit_intercept=True)
reg.fit(xTrain_encode,yTrain)
print(reg.coef_,reg.intercept_)

print(reg.score(X=xTest_encode,y=yTest))
err = reg.predict(xTest_encode)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err**2)))

[-650279.35885789 -650279.35885864  650279.35885827] 0.004608501005075329
-1.033814799322741e-06
0.008340300693903993


In [19]:
xTrain_encode

[[6, 13, 19],
 [12, 13, 25],
 [3, 32, 35],
 [10, 16, 26],
 [15, 22, 37],
 [13, 1, 14],
 [2, 1, 3],
 [20, 35, 55],
 [7, 1, 8],
 [15, 1, 16],
 [6, 14, 20],
 [15, 16, 31],
 [8, 4, 12],
 [11, 17, 28],
 [11, 17, 28],
 [15, 9, 24],
 [14, 21, 35],
 [13, 5, 18],
 [21, 30, 51],
 [19, 14, 33],
 [13, 2, 15],
 [24, 13, 37],
 [17, 24, 41],
 [3, 6, 9],
 [1, 20, 21],
 [19, 25, 44],
 [14, 15, 29],
 [1, 31, 32],
 [21, 2, 23],
 [10, 3, 13],
 [7, 8, 15],
 [7, 29, 36],
 [3, 14, 17],
 [14, 19, 33],
 [22, 24, 46],
 [2, 12, 14],
 [9, 34, 43],
 [2, 3, 5],
 [1, 5, 6],
 [22, 5, 27],
 [12, 35, 47],
 [6, 31, 37],
 [2, 20, 22],
 [1, 20, 21],
 [8, 8, 16],
 [10, 5, 15],
 [22, 11, 33],
 [5, 31, 36],
 [23, 24, 47],
 [24, 1, 25],
 [20, 2, 22],
 [16, 2, 18],
 [17, 25, 42],
 [23, 34, 57],
 [22, 28, 50],
 [17, 2, 19],
 [1, 26, 27],
 [16, 25, 41],
 [4, 2, 6],
 [6, 7, 13],
 [11, 10, 21],
 [21, 31, 52],
 [19, 33, 52],
 [19, 14, 33],
 [6, 4, 10],
 [19, 1, 20],
 [3, 26, 29],
 [11, 22, 33],
 [20, 6, 26],
 [19, 2, 21],
 [6, 11, 

In [20]:
from sklearn.linear_model import Ridge
clf1 = Ridge(alpha=1)
clf1.fit(xTrain_encode,yTrain)
print(clf1.coef_,clf1.intercept_)

print(clf1.score(X=xTest_encode,y=yTest))
err1 = clf1.predict(xTest_encode)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err1**2)))

[ 6.96173731e-07 -4.70429642e-07  2.25746812e-07] 0.004599443898848887
-1.508306605391141e-06
0.008340302672603883


In [21]:
from sklearn.linear_model import Ridge
clf2 = Ridge(alpha=10000000000000000000000)
clf2.fit(xTrain_encode,yTrain)
print(clf2.coef_,clf1.intercept_)

print(clf2.score(X=xTest_encode,y=yTest))
err2 = clf2.predict(xTest_encode)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err1**2)))

[ 8.09062370e-21 -4.76132143e-21  3.32930226e-21] 0.004599443898848887
-8.32382043292057e-07
0.008340302672603883


## Normalization(error increased)

In [22]:
from sklearn.preprocessing import normalize
#xTrain_norm = []
#train['norm_t'] = normalize(train['t'])
#train['norm_t'] = normalize(np.array(train['t']).reshape(-1, 1))
#train['norm_v'] = normalize(np.array(train['v']).reshape(-1, 1))

#for i in train.index:
#    d = []
#    t = train._get_value(i, 'norm_t')
#    d.append(train._get_value(i, 'norm_t'))
#    d.append(train._get_value(i,'norm_v'))
#    xTrain_norm.append(d)


xTrain_norm = normalize(xTrain)

#xTest_norm = []
#test['norm_t'] = normalize(np.array(test['t']).reshape(-1, 1))
#test['norm_v'] = normalize(np.array(test['v']).reshape(-1, 1))
#for i in test.index:
#    d = []
#    d.append(test._get_value(i, 'norm_t'))
#    d.append(test._get_value(i, 'norm_v'))
#    xTest_norm.append(d)

xTest_norm = normalize(xTest)


#yTrain = train['x4']
#yTest = test['x4']

print(len(xTrain_norm),len(xTest_norm),len(yTrain),len(yTest))

1820165 455042 1820165 455042


In [23]:
from sklearn import linear_model
reg1=linear_model.LinearRegression(fit_intercept=True)
reg1.fit(xTrain_norm,yTrain)
print(reg1.coef_,reg.intercept_)

[ 262911.63316554  262911.64092818 -262911.59453258] 0.004608501005075329


In [24]:
reg1.score(X=xTest_norm,y=yTest)

0.03530545062093193

In [25]:
err = reg1.predict(xTest_norm)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err**2)))

0.008191744466803996


# OLS

In [26]:
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import pandas as pd

ModuleNotFoundError: No module named 'statsmodels'

In [ ]:
data = pd.read_csv('simDTS.csv')
#data = pd.read_csv('src/visualization/simDTS.csv')

In [ ]:
from sklearn import model_selection
train, test = model_selection.train_test_split(data, test_size=0.2) 
nSample = len(train.index)
x=sm.add_constant(train['v'])
est=sm.OLS(train['x4'],train['v'])
model=est.fit()
print(model.summary())

                                 OLS Regression Results                                
Dep. Variable:                     x4   R-squared (uncentered):                   0.002
Model:                            OLS   Adj. R-squared (uncentered):              0.002
Method:                 Least Squares   F-statistic:                              3149.
Date:                Wed, 09 Nov 2022   Prob (F-statistic):                        0.00
Time:                        12:02:11   Log-Likelihood:                     -1.3332e+06
No. Observations:             1906673   AIC:                                  2.666e+06
Df Residuals:                 1906672   BIC:                                  2.667e+06
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [ ]:
#model.rsquared

In [ ]:
err = model.predict(test['v'])-test['x4']
#print(err)
#np.mean(err)
print(np.sqrt(np.mean(err**2)))

0.4875809777799
